### ISSUE TITLE
Sequence download

### ISSUE THREAD

**Issue by johanneskoester** [koesterlab/snakemake-workflow-sars-cov2#2]
I've read a bit through the nextstrain docs and found the following statement (see [here](https://docs.nextstrain.org/en/latest/guides/share/download-data.html):
> We make it possible to download the derived data behind the visualisations on nextstrain.org for your own further analysis. We’ve made the decision not to make the sequence data downloadable as a lot of the original data sources have data sharing restrictions which this would violate. The genbank & GISAID accessions, if applicable, are contained in the metadata download should you wish to access the original sequence data.

In other words, seems like only genbank and GISAID are sources for sequences, and this will definitely be a subset. In case GISAID should provide additional ones to genbank, one has to apply for access [here](https://www.gisaid.org/registration/register/).

Finally, I went through the nextstrain visualizations, and actually the names like `Spain/M-20224207/2020` seem to be the official ones. Hence, the FASTA headers that we get from genbank should be fine, as they contain these names as well.

**Comment by thomasbtf** [comment]
Related with #50
