### ISSUE TITLE
Custom summary table in Snakemake report for virologist

### ISSUE THREAD

**Issue by thomasbtf** [koesterlab/snakemake-workflow-sars-cov2#47]
Use the 

- existing analyse_contigs.py script and
- the [rbt](https://github.com/rust-bio/rust-bio-tools) csv-report subcommand 

to generate an interactive summary report of the following structure:

![image](https://user-images.githubusercontent.com/46334240/107982490-727d0080-6fc4-11eb-84a1-be268c24efd0.png)

For information about the mutations, the subclonal .bcf file (in results/calls/ref~main/) can be used. 
Necessary information from this file is:

- [x] HGVSp from the ANN field

Additional, useful information we could to virologists are:

- [x] IMPACT from the ANN field
- [x] Allele frequency (AF) from the ANN field

The output from the rbt output should be integrated into the Snakemake report.
Moreover, a rule to produce the Snakemake report (for the current run) should be added.

1. Generate csv file for table displayed above.
2. Use RBT csv-report
3. Integrate csv-report in Snakemake report

**Comment by alethomas** [comment]
#88
