### ISSUE TITLE
Add date folders for results

### ISSUE THREAD

**Issue by alethomas** [koesterlab/snakemake-workflow-sars-cov2#60]

**Comment by alethomas** [comment]
move indices from results to resources

**Comment by thomasbtf** [comment]
- [ ] date substructure in results folder
- [ ] date substructure in logs folder
- [ ] large indices in resources
- [ ] pangolin update in results ?
- [ ] mutliqc per run
- [ ] update benchmarking acc. to new structure
- [ ] update preprocessing/update_sample_sheet.py
- [ ] handling of varient calling "all"
